name: Compilar APK WearOS

# Cancelar ejecuciones antiguas automáticamente
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

run-name: >-
  ${{
    github.event_name == 'workflow_dispatch'
    && format('Compilación manual: {0}', github.event.inputs.motivo)
    || format('Commit: {0}', github.event.head_commit.message)
  }}
  
on:
  push:
    branches: [ "main" ] # Se ejecutará automáticamente al guardar aquí

  workflow_dispatch:
    inputs:
      motivo:
        description: "Título de la ejecución"
        required: true
        default: "Compilación manual"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # Paso clave: Instala el motor oficial de Android y Gradle de forma automática en el servidor
    - name: Configurar Entorno Oficial de Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.2"

    # Compila tu APK directamente usando el comando del sistema inyectado de forma segura
    - name: Compilar APK (Debug)
      run: gradle assembleDebug --no-daemon

    - name: Guardar y mostrar el APK generado
      uses: actions/upload-artifact@v4
      with:
        name: Full Digital Clock
        path: "**/build/outputs/apk/debug/*.apk"
        retention-days: 1
        if-no-files-found: error
